### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by dallasjanssen** [jfarmer08/homebridge-wyze-smart-home#229]
**Describe The Bug:**
Randomly a few weeks ago my homebridge was lagging, when I checked the logs I saw Wyze was failing endlessly.  I disabled it and due to a busy schedule didn’t revist until this week.  Updated to the latest version and problem persists. Got a new API key and removed the config and re-setup. Issue persists. 

**To Reproduce:**
Enable plugin and start homebridge service.  

**Expected behavior:**
Login and fetch devices. 

**Logs:**
[2/26/2024, 10:02:20 PM] [Wyze] Wyze API Error (2002): 'RefreshTokenError'
[2/26/2024, 10:02:20 PM] [Wyze] Error getting devices: Error: Refresh Token could not be used to get a new access token. Error: Wyze API Error (2002) - RefreshTokenError
[2/26/2024, 10:03:20 PM] [Wyze] Wyze API Error (2001): 'access token is error'
[2/26/2024, 10:03:21 PM] [Wyze] Wyze API Error (2002): 'RefreshTokenError'
[2/26/2024, 10:03:21 PM] [Wyze] Error getting devices: Error: Refresh Token could not be used to get a new access token. Error: Wyze API Error (2002) - RefreshTokenError

**Plugin Config:**

"name": "Wyze",
            "username": "(email)",
            "password": "(pw)",
            "keyId": "(key)",
            "apiKey": "(key)",
            "refreshInterval": 60000,
            "hms": true,
            "showAdvancedOptions": true,
            "apiLogEnabled": false,
            "pluginLoggingEnabled": false,
            "lowBatteryPercentage": 30,
            "excludeMacAddress": false,
            "excludedeviceType": true,
            "filterDeviceTypeList": [
                "Camera"
            ],
            "platform": "WyzeSmartHome"

**Environment:**

* **Plugin Version**: 0.5.54
* **Homebridge Version**: 1.7.0
* **Node.js Version**: v18.19.0
* **Operating System**: Docker / Ubuntu Jammy Jellyfish (22.04.3 LTS)

**Comment by jfarmer08** [comment]
I have seen this, you need to delete the stored access token. You can find it in the persist directory for homebridge.

**Comment by ceedveed** [comment]
> persist directory

where is this for a windows install please?

**Comment by dallasjanssen** [comment]
I have cleared my whole persistent volume and the error persists.  Is there
any other troubleshooting you would recommend?

**Comment by jfarmer08** [comment]
Can you turn logging on? That might help give me more ideas. Also does your API Key or  KEY Id have any special characters?

**Comment by ceedveed** [comment]
> I have cleared my whole persistent volume and the error persists. Is there any other troubleshooting you would recommend?

For me I had to:

- delete stored token in the persist folder (has wyze in the file name)
- reset password
- enter new password in wyze plugin

My API key and Key ID did not change. I don't know why I was getting the same errors as you suddenly. But my steps above fixed it.

**Comment by dallasjanssen** [comment]
My key id does have special characters, it is broken up my dashes.

Here is the plugin logs.

[2/27/2024, 8:36:15 PM] [Wyze] Restarting child bridge... [2/27/2024,
8:36:15 PM] Got SIGTERM, shutting down child bridge process... [2/27/2024,
8:36:20 PM] [Wyze] Child bridge process ended [2/27/2024, 8:36:20 PM]
[Wyze] Process Ended. Code: 143, Signal: null [2/27/2024, 8:36:27 PM]
[Wyze] Restarting Process... [2/27/2024, 8:36:29 PM] [Wyze] Launched child
bridge with PID 1938 [2/27/2024, 8:36:29 PM] Registering platform
'homebridge-wyze-smart-home.WyzeSmartHome' [2/27/2024, 8:36:29 PM] [Wyze]
Loaded homebridge-wyze-smart-home v0.5.45 child bridge successfully
[2/27/2024, 8:36:29 PM] Loaded 0 cached accessories from
cachedAccessories.0E6B23AC20A7. [2/27/2024, 8:36:29 PM] [Wyze] Refreshing
devices... [2/27/2024, 8:36:29 PM] Homebridge v1.7.0 (HAP v0.11.1) (Wyze)
is running on port 44650. [2/27/2024, 8:36:29 PM] [Wyze] Performing
request:
{"method":"POST","url":"app/v2/home_page/get_object_list","data":{"access_token":"lvtx./4vNpPQz5Y2iobwbYbtHykIybR0kmJPHNw87WQQaUV1C+z+d/KcNuvagbEUcGBPmedcA5BOQdWDA5JIHXkkD19rbffE66yEUSuVzmcGtAcorgL1AtTINYuqffdLUhePCWibSkX0zkhou9L8jjvzPLRD5sz0L38d4Nn69Oo7YK1Ljsc4cbg2r/5l7CIhFjjgovD5iHA==","app_name":"com.hualai.WyzeCam","app_ver":"wyze_developer_api","app_version":"wyze_developer_api","phone_id":"wyze_developer_api","phone_system_type":"1","sc":"wyze_developer_api","sv":"wyze_developer_api","ts":1709087789980},"baseURL":"
https://api.wyzecam.com"} [2/27/2024, 8:36:30 PM] [Wyze] API response
PerformRequest:
{"url":"app/v2/home_page/get_object_list","status":200,"data":{"code":"2001","msg":"access
token is
error","traceId":"b9523e22eda82b30ff47f951637f2529","data":{}},"headers":{"date":"Wed,
28 Feb 2024 02:36:30
GMT","content-type":"application/json","content-length":"100","connection":"close","x-ratelimit-remaining":"298","x-ratelimit-reset-by":"Wed
Feb 28 02:38:52 GMT
2024","access-control-allow-origin":"*","access-control-allow-methods":"POST","access-control-allow-headers":"token","access-control-max-age":"1800","vary":"Origin,
Access-Control-Request-Method, Access-Control-Request-Headers"}}
[2/27/2024, 8:36:30 PM] [Wyze] API rate limit remaining: 298. Expires in
141062ms [2/27/2024, 8:36:30 PM] [Wyze] Wyze API Error (2001): 'access
token is error' [2/27/2024, 8:36:30 PM] [Wyze] Performing request:
{"method":"POST","url":"app/user/refresh_token","data":{"access_token":"","app_name":"com.hualai.WyzeCam","app_ver":"wyze_developer_api","app_version":"wyze_developer_api","phone_id":"wyze_developer_api","phone_system_type":"1","sc":"wyze_developer_api","sv":"wyze_developer_api","ts":1709087790942,"refresh_token":"lvtx.1QAi1s8S1Av+O9oxO5R39plzHOw+uK2AqWx2tovuRaPfp8KcX2EdvmIt6urpXD66WKX8SluYGY9jvTpr5e8jUhAmnRKNZfAFygetqkbTMpv8U8BoMSwWlDuL8RYENHoVhhcFRvJ6tpgJSMkLABJGOfnR9+nMTACAJzw+2qSEXiTnVJaZZrC3++cuj0kWQ6dHdpgfuA=="},"baseURL":"
https://api.wyzecam.com"} [2/27/2024, 8:36:31 PM] [Wyze] API response
PerformRequest:
{"url":"app/user/refresh_token","status":200,"data":{"ts":1709087791334,"code":"2002","msg":"RefreshTokenError","data":{}},"headers":{"date":"Wed,
28 Feb 2024 02:36:31 GMT","content-type":"application/json;
charset=utf-8","content-length":"70","connection":"close","x-ratelimit-remaining":"298","x-ratelimit-reset-by":"Wed
Feb 28 02:38:54 GMT
2024","cache-control":"no-cache","pragma":"no-cache","expires":"-1","server":"Microsoft-IIS/8.5","access-control-allow-headers":"Origin,
X-Requested-With, Content-Type, Cache-Control, Accept, authorization,
content-type","access-control-allow-methods":"POST,GET,OPTIONS","access-control-allow-origin":"*","x-aspnet-version":"4.0.30319","x-powered-by":"
ASP.NET"}} [2/27/2024, 8:36:31 PM] [Wyze] API rate limit remaining: 298.
Expires in 142566ms [2/27/2024, 8:36:31 PM] [Wyze] Wyze API Error (2002):
'RefreshTokenError' [2/27/2024, 8:36:31 PM] [Wyze] Error getting devices:
Error: Refresh Token could not be used to get a new access token. Error:
Wyze API Error (2002) - RefreshTokenError

**Comment by dallasjanssen** [comment]
This did it!

I tried a few times and also deleted and got a new key and ID but I am up
and running!! Thanks for the help. This can be closed!

**Comment by shanekelly55** [comment]
Hey Team,

Getting this too.  I reset my password but still getting some error.  Where in Homebridge do I delete everything in the persist folder?  Sorry, a bit of a newb here.

**Comment by dallasjanssen** [comment]
What are you running homebridge on?

**Comment by shanekelly55** [comment]
It is a raspberry pi so I assume Ubuntu.

**Comment by carTloyal123** [comment]
Looks like this is resolved, thanks everyone!

**Comment by dapostman** [comment]
I think this still needs to be open. Same error continues here with same actions taken. Only difference is running on macOS.

**Comment by jfarmer08** [comment]
Maybe some logs would be helpful

Thanks Allen :)

**Comment by csytsma** [comment]
Posting my process, in case it helps anyone else. I'm running Homebridge on a Synology DS218+. 
Homebridge: v1.6.0
Wyze Plugin: homebridge-wyze-smart-home v0.5.46

My sequence, which worked in the end:
- Reset Wyze password on their site
- Create new Wyze keys on their site
- Entered new password and keys in Homebridge
- NOTE: this didn't fix the problem, same errors after restart
- Delete the 2 wyze-****.json files in /var/packages/homebridge/shares/homebridge/persist
  - open Terminal, cd to persist folder, rm wyze-****.json
- Open wyze plugin in Homebridge, confirm password and keys are still there, Save plugin
- Restart Homebridge

Booted up fine with no more errors.

**Comment by KyleStilkey** [comment]
> Posting my process, in case it helps anyone else. I'm running Homebridge on a Synology DS218+. Homebridge: v1.6.0 Wyze Plugin: homebridge-wyze-smart-home v0.5.46
> 
> My sequence, which worked in the end:
> 
> * Reset Wyze password on their site
> * Create new Wyze keys on their site
> * Entered new password and keys in Homebridge
> * NOTE: this didn't fix the problem, same errors after restart
> * Delete the 2 wyze-****.json files in /var/packages/homebridge/shares/homebridge/persist
>   
>   * open Terminal, cd to persist folder, rm wyze-****.json
> * Open wyze plugin in Homebridge, confirm password and keys are still there, Save plugin
> * Restart Homebridge
> 
> Booted up fine with no more errors.

Tried this but says the directory packages doesn't exist. Not sure what the command is to see the directory listings so I can find these files and remove them.

**Comment by kaltechlin35** [comment]
> Posting my process, in case it helps anyone else. I'm running Homebridge on a Synology DS218+. Homebridge: v1.6.0 Wyze Plugin: homebridge-wyze-smart-home v0.5.46
> 
> My sequence, which worked in the end:
> 
> * Reset Wyze password on their site
> * Create new Wyze keys on their site
> * Entered new password and keys in Homebridge
> * NOTE: this didn't fix the problem, same errors after restart
> * Delete the 2 wyze-****.json files in /var/packages/homebridge/shares/homebridge/persist
>   
>   * open Terminal, cd to persist folder, rm wyze-****.json
> * Open wyze plugin in Homebridge, confirm password and keys are still there, Save plugin
> * Restart Homebridge
> 
> Booted up fine with no more errors.

This is exactly what fixed my issue! Thank you very much!

**Comment by eriktheviking** [comment]
Question... how do I get to the persist directory within Hombridge on a Raspberry Pi 4?

**Comment by dapostman** [comment]
"/var/lib/homebridge": This is the standard directory where Homebridge stores its configuration files, including the "persist" folder which holds data related to accessory states and other persistent information. 
Little bit of DuckDuckGo or Google is helpful.

jp
